### Login Request to retrieve a token

POST http://localhost:4004/auth/login
Content-Type: application/json

{
  "email": "user.salmen@gmail.com",
  "password": "password"
}

> {% client.global.set("token", response.body.token) %}

###